name: HBit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  date_format: ^1.0.8
  flutter_cupertino_date_picker: ^1.0.12
  fluro: ^1.7.8
  flutter_screenutil: ^1.0.2
  dio: ^3.0.8
  cookie_jar: ^ 1.0.0
  pull_to_refresh: ^1.6.3
  provider: ^4.0.3
  gzx_dropdown_menu: ^1.0.1
  pin_code_text_field: ^1.5.1
  device_info: ^0.4.2+4
  uuid: ^2.0.4
  shared_preferences: ^0.5.6+2
  fluttertoast: ^3.1.3
  barcode_scan: ^3.0.1 
  collection: ^1.14.11
  unique_id: ^0.0.2
  flutter_swiper: ^1.1.6 
  extended_image: ^0.7.3+1 
  event_bus: ^1.1.1 
  qr_flutter: ^3.1.0 
  image_gallery_saver: ^1.2.2 
  permission_handler: ^5.0.0+hotfix.5 
  image_picker: ^0.6.6+1 
  bot_toast: ^3.0.0 
  percent_indicator: ^2.1.3 
  flutter_app_upgrade: ^1.0.2 
  path_provider: ^1.6.5
  shimmer: ^1.0.0 
  loading_indicator_view: ^1.1.0
  url_launcher: ^5.4.7 
  localstorage: ^2.0.0 
  package_info: ^0.4.0+16 
  gallery_saver: ^2.0.1 
  flutter_html: ^1.0.0 
  json_serializable: ^2.2.1
  rxdart: ^0.21.0
  http: ^0.12.0+2
  webview_flutter: ^1.0.2
  sy_flutter_qiniu_storage: ^0.2.1 
  common_utils: ^1.2.1 
  fsuper: ^0.1.5 
  extended_nested_scroll_view: ^0.4.0
  encrypt: ^4.0.2 
  flutter_picker: ^1.1.5
  k_chart: ^0.1.2
  syncfusion_flutter_charts: ^18.3.51
  flutter_k_chart:
      path: ./plugin/flutter_k_chart  #k线图
  flutter_seekbar:
    git: https://github.com/LiuC520/flutter_seekbar.git 
  cool_ui: ^0.6.3 
  steel_crypt: ^1.5.3
  cupertino_icons: ^1.0.0
  transparent_image: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/home/
    - images/login/
    - images/contract/
    - images/mine/
    - images/splash/
    - images/tabBar/
    - images/trade/
    - images/assets/
    - images/c2c/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
